# Generated by Django 5.2.12 on 2026-03-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0016_alter_imprimirdieta_carb_31_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.PositiveSmallIntegerField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('alimento', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('kcal', models.IntegerField(default=0)),
                ('prot', models.IntegerField(default=0)),
                ('gord', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nutri.imprimirdieta')),
            ],
            options={
                'ordering': ['refeicao', 'ordem', 'id'],
            },
        ),
    ]
