# Generated by Codex on 2026-03-09

from django.db import migrations


def _parse_int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def forwards(apps, schema_editor):
    ImprimirDieta = apps.get_model("nutri", "ImprimirDieta")
    ItemRefeicao = apps.get_model("nutri", "ItemRefeicao")

    to_create = []
    for dieta in ImprimirDieta.objects.all().iterator():
        for refeicao in range(1, 7):
            for ordem in range(1, 4):
                sufixo = f"{refeicao}{ordem}"
                alimento = str(getattr(dieta, f"ref_{sufixo}", "") or "").strip()
                quantidade = _parse_int(getattr(dieta, f"quant_{sufixo}", 0))
                kcal = _parse_int(getattr(dieta, f"kcal_{sufixo}", 0))
                prot = _parse_int(getattr(dieta, f"prot_{sufixo}", 0))
                gord = _parse_int(getattr(dieta, f"gord_{sufixo}", 0))
                carb = _parse_int(getattr(dieta, f"carb_{sufixo}", 0))

                if not alimento or quantidade <= 0:
                    continue

                to_create.append(
                    ItemRefeicao(
                        dieta_id=dieta.id,
                        refeicao=refeicao,
                        ordem=ordem,
                        alimento=alimento,
                        quantidade=quantidade,
                        kcal=kcal,
                        prot=prot,
                        gord=gord,
                        carb=carb,
                    )
                )

    if to_create:
        ItemRefeicao.objects.bulk_create(to_create)


def backwards(apps, schema_editor):
    ImprimirDieta = apps.get_model("nutri", "ImprimirDieta")
    ItemRefeicao = apps.get_model("nutri", "ItemRefeicao")

    for dieta in ImprimirDieta.objects.all().iterator():
        for refeicao in range(1, 7):
            for ordem in range(1, 4):
                sufixo = f"{refeicao}{ordem}"
                setattr(dieta, f"ref_{sufixo}", "")
                setattr(dieta, f"quant_{sufixo}", 0)
                setattr(dieta, f"kcal_{sufixo}", 0)
                setattr(dieta, f"prot_{sufixo}", 0)
                setattr(dieta, f"gord_{sufixo}", 0)
                setattr(dieta, f"carb_{sufixo}", 0)

        itens = ItemRefeicao.objects.filter(dieta_id=dieta.id).order_by("refeicao", "ordem", "id")
        counters = {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
        for item in itens:
            slot = counters.get(item.refeicao, 4)
            if slot > 3:
                continue

            sufixo = f"{item.refeicao}{slot}"
            setattr(dieta, f"ref_{sufixo}", item.alimento)
            setattr(dieta, f"quant_{sufixo}", item.quantidade)
            setattr(dieta, f"kcal_{sufixo}", item.kcal)
            setattr(dieta, f"prot_{sufixo}", item.prot)
            setattr(dieta, f"gord_{sufixo}", item.gord)
            setattr(dieta, f"carb_{sufixo}", item.carb)
            counters[item.refeicao] = slot + 1

        dieta.save()


class Migration(migrations.Migration):

    dependencies = [
        ("nutri", "0017_itemrefeicao"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

