# Generated by Django 5.2.12 on 2026-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0018_migrate_items_from_legacy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemrefeicao',
            index=models.Index(fields=['dieta', 'refeicao', 'ordem'], name='item_ref_dieta_ord_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemrefeicao',
            constraint=models.CheckConstraint(condition=models.Q(('refeicao__gte', 1), ('refeicao__lte', 6)), name='item_refeicao_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='itemrefeicao',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gte', 1)), name='item_ordem_positive_ck'),
        ),
    ]
